/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthenticatedVenturesRouteImport } from './routes/_authenticated/ventures'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedAccountabilityRouteImport } from './routes/_authenticated/accountability'
import { Route as AuthenticatedVenturesIdRouteImport } from './routes/_authenticated/ventures.$id'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedKnowledgeIdRouteImport } from './routes/_authenticated/knowledge.$id'
import { Route as AuthenticatedGoalsIdRouteImport } from './routes/_authenticated/goals.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedDecisionsIdRouteImport } from './routes/_authenticated/decisions.$id'
import { Route as AuthenticatedCommitmentsIdRouteImport } from './routes/_authenticated/commitments.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedVenturesRoute = AuthenticatedVenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountabilityRoute =
  AuthenticatedAccountabilityRouteImport.update({
    id: '/accountability',
    path: '/accountability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVenturesIdRoute = AuthenticatedVenturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVenturesRoute,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedKnowledgeIdRoute =
  AuthenticatedKnowledgeIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedGoalsIdRoute = AuthenticatedGoalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedGoalsRoute,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedDecisionsIdRoute =
  AuthenticatedDecisionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDecisionsRoute,
  } as any)
const AuthenticatedCommitmentsIdRoute =
  AuthenticatedCommitmentsIdRouteImport.update({
    id: '/commitments/$id',
    path: '/commitments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/accountability': typeof AuthenticatedAccountabilityRoute
  '/decisions': typeof AuthenticatedDecisionsRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/operator': typeof AuthenticatedOperatorRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/ventures': typeof AuthenticatedVenturesRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/commitments/$id': typeof AuthenticatedCommitmentsIdRoute
  '/decisions/$id': typeof AuthenticatedDecisionsIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/ventures/$id': typeof AuthenticatedVenturesIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/accountability': typeof AuthenticatedAccountabilityRoute
  '/decisions': typeof AuthenticatedDecisionsRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/operator': typeof AuthenticatedOperatorRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/ventures': typeof AuthenticatedVenturesRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/': typeof AuthenticatedIndexRoute
  '/commitments/$id': typeof AuthenticatedCommitmentsIdRoute
  '/decisions/$id': typeof AuthenticatedDecisionsIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/ventures/$id': typeof AuthenticatedVenturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/accountability': typeof AuthenticatedAccountabilityRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRouteWithChildren
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/ventures': typeof AuthenticatedVenturesRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/commitments/$id': typeof AuthenticatedCommitmentsIdRoute
  '/_authenticated/decisions/$id': typeof AuthenticatedDecisionsIdRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/_authenticated/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/ventures/$id': typeof AuthenticatedVenturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/accountability'
    | '/decisions'
    | '/documents'
    | '/goals'
    | '/integrations'
    | '/knowledge'
    | '/operator'
    | '/projects'
    | '/settings'
    | '/ventures'
    | '/auth/forgot'
    | '/auth/reset'
    | '/commitments/$id'
    | '/decisions/$id'
    | '/documents/$id'
    | '/goals/$id'
    | '/knowledge/$id'
    | '/projects/$id'
    | '/ventures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/accountability'
    | '/decisions'
    | '/documents'
    | '/goals'
    | '/integrations'
    | '/knowledge'
    | '/operator'
    | '/projects'
    | '/settings'
    | '/ventures'
    | '/auth/forgot'
    | '/auth/reset'
    | '/'
    | '/commitments/$id'
    | '/decisions/$id'
    | '/documents/$id'
    | '/goals/$id'
    | '/knowledge/$id'
    | '/projects/$id'
    | '/ventures/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/accountability'
    | '/_authenticated/decisions'
    | '/_authenticated/documents'
    | '/_authenticated/goals'
    | '/_authenticated/integrations'
    | '/_authenticated/knowledge'
    | '/_authenticated/operator'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/ventures'
    | '/auth/forgot'
    | '/auth/reset'
    | '/_authenticated/'
    | '/_authenticated/commitments/$id'
    | '/_authenticated/decisions/$id'
    | '/_authenticated/documents/$id'
    | '/_authenticated/goals/$id'
    | '/_authenticated/knowledge/$id'
    | '/_authenticated/projects/$id'
    | '/_authenticated/ventures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/ventures': {
      id: '/_authenticated/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof AuthenticatedVenturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accountability': {
      id: '/_authenticated/accountability'
      path: '/accountability'
      fullPath: '/accountability'
      preLoaderRoute: typeof AuthenticatedAccountabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventures/$id': {
      id: '/_authenticated/ventures/$id'
      path: '/$id'
      fullPath: '/ventures/$id'
      preLoaderRoute: typeof AuthenticatedVenturesIdRouteImport
      parentRoute: typeof AuthenticatedVenturesRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/knowledge/$id': {
      id: '/_authenticated/knowledge/$id'
      path: '/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof AuthenticatedKnowledgeIdRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/goals/$id': {
      id: '/_authenticated/goals/$id'
      path: '/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof AuthenticatedGoalsIdRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/decisions/$id': {
      id: '/_authenticated/decisions/$id'
      path: '/$id'
      fullPath: '/decisions/$id'
      preLoaderRoute: typeof AuthenticatedDecisionsIdRouteImport
      parentRoute: typeof AuthenticatedDecisionsRoute
    }
    '/_authenticated/commitments/$id': {
      id: '/_authenticated/commitments/$id'
      path: '/commitments/$id'
      fullPath: '/commitments/$id'
      preLoaderRoute: typeof AuthenticatedCommitmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDecisionsRouteChildren {
  AuthenticatedDecisionsIdRoute: typeof AuthenticatedDecisionsIdRoute
}

const AuthenticatedDecisionsRouteChildren: AuthenticatedDecisionsRouteChildren =
  {
    AuthenticatedDecisionsIdRoute: AuthenticatedDecisionsIdRoute,
  }

const AuthenticatedDecisionsRouteWithChildren =
  AuthenticatedDecisionsRoute._addFileChildren(
    AuthenticatedDecisionsRouteChildren,
  )

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedGoalsRouteChildren {
  AuthenticatedGoalsIdRoute: typeof AuthenticatedGoalsIdRoute
}

const AuthenticatedGoalsRouteChildren: AuthenticatedGoalsRouteChildren = {
  AuthenticatedGoalsIdRoute: AuthenticatedGoalsIdRoute,
}

const AuthenticatedGoalsRouteWithChildren =
  AuthenticatedGoalsRoute._addFileChildren(AuthenticatedGoalsRouteChildren)

interface AuthenticatedKnowledgeRouteChildren {
  AuthenticatedKnowledgeIdRoute: typeof AuthenticatedKnowledgeIdRoute
}

const AuthenticatedKnowledgeRouteChildren: AuthenticatedKnowledgeRouteChildren =
  {
    AuthenticatedKnowledgeIdRoute: AuthenticatedKnowledgeIdRoute,
  }

const AuthenticatedKnowledgeRouteWithChildren =
  AuthenticatedKnowledgeRoute._addFileChildren(
    AuthenticatedKnowledgeRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedVenturesRouteChildren {
  AuthenticatedVenturesIdRoute: typeof AuthenticatedVenturesIdRoute
}

const AuthenticatedVenturesRouteChildren: AuthenticatedVenturesRouteChildren = {
  AuthenticatedVenturesIdRoute: AuthenticatedVenturesIdRoute,
}

const AuthenticatedVenturesRouteWithChildren =
  AuthenticatedVenturesRoute._addFileChildren(
    AuthenticatedVenturesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountabilityRoute: typeof AuthenticatedAccountabilityRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRouteWithChildren
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRouteWithChildren
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVenturesRoute: typeof AuthenticatedVenturesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCommitmentsIdRoute: typeof AuthenticatedCommitmentsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountabilityRoute: AuthenticatedAccountabilityRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRouteWithChildren,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRouteWithChildren,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVenturesRoute: AuthenticatedVenturesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCommitmentsIdRoute: AuthenticatedCommitmentsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
