/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalTokenRouteImport } from './routes/proposal.$token'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as AuthenticatedVenturesRouteImport } from './routes/_authenticated/ventures'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedContentOpsRouteImport } from './routes/_authenticated/content-ops'
import { Route as AuthenticatedAccountabilityRouteImport } from './routes/_authenticated/accountability'
import { Route as AuthenticatedSamIndexRouteImport } from './routes/_authenticated/sam.index'
import { Route as AuthenticatedLabsIndexRouteImport } from './routes/_authenticated/labs.index'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsFounderActivationRouteImport } from './routes/_authenticated/settings.founder-activation'
import { Route as AuthenticatedSamMemoryRouteImport } from './routes/_authenticated/sam.memory'
import { Route as AuthenticatedSamIntegrationsRouteImport } from './routes/_authenticated/sam.integrations'
import { Route as AuthenticatedSamControlRouteImport } from './routes/_authenticated/sam.control'
import { Route as AuthenticatedSamContentRouteImport } from './routes/_authenticated/sam.content'
import { Route as AuthenticatedLabsVenturesRouteImport } from './routes/_authenticated/labs.ventures'
import { Route as AuthenticatedLabsRevenueRouteImport } from './routes/_authenticated/labs.revenue'
import { Route as AuthenticatedLabsProjectsRouteImport } from './routes/_authenticated/labs.projects'
import { Route as AuthenticatedLabsOperatorRouteImport } from './routes/_authenticated/labs.operator'
import { Route as AuthenticatedLabsMissionControlRouteImport } from './routes/_authenticated/labs.mission-control'
import { Route as AuthenticatedLabsKnowledgeRouteImport } from './routes/_authenticated/labs.knowledge'
import { Route as AuthenticatedLabsGoalsRouteImport } from './routes/_authenticated/labs.goals'
import { Route as AuthenticatedLabsDocumentsRouteImport } from './routes/_authenticated/labs.documents'
import { Route as AuthenticatedLabsDecisionsRouteImport } from './routes/_authenticated/labs.decisions'
import { Route as AuthenticatedLabsBillingRouteImport } from './routes/_authenticated/labs.billing'
import { Route as AuthenticatedLabsAccountabilityRouteImport } from './routes/_authenticated/labs.accountability'
import { Route as AuthenticatedLabsProposalsIndexRouteImport } from './routes/_authenticated/labs.proposals.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicProposalsViewRouteImport } from './routes/api/public/proposals/view'
import { Route as ApiPublicProposalsPdfRouteImport } from './routes/api/public/proposals/pdf'
import { Route as ApiPublicProposalsDeclineRouteImport } from './routes/api/public/proposals/decline'
import { Route as ApiPublicProposalsAcceptRouteImport } from './routes/api/public/proposals/accept'
import { Route as ApiPublicAutomationTickRouteImport } from './routes/api/public/automation/tick'
import { Route as ApiPublicAutomationSchedulerRouteImport } from './routes/api/public/automation/scheduler'
import { Route as AuthenticatedSettingsIntegrationsNewRouteImport } from './routes/_authenticated/settings.integrations.new'
import { Route as AuthenticatedSettingsIntegrationsConnectionIdRouteImport } from './routes/_authenticated/settings.integrations.$connectionId'
import { Route as AuthenticatedSamMissionsIdRouteImport } from './routes/_authenticated/sam.missions.$id'
import { Route as AuthenticatedSamIntegrationsWebhooksRouteImport } from './routes/_authenticated/sam.integrations.webhooks'
import { Route as AuthenticatedSamIntegrationsRestEndpointsRouteImport } from './routes/_authenticated/sam.integrations.rest-endpoints'
import { Route as AuthenticatedSamContentLibraryRouteImport } from './routes/_authenticated/sam.content.library'
import { Route as AuthenticatedSamContentCalendarRouteImport } from './routes/_authenticated/sam.content.calendar'
import { Route as AuthenticatedLabsVenturesIdRouteImport } from './routes/_authenticated/labs.ventures.$id'
import { Route as AuthenticatedLabsProposalsIdRouteImport } from './routes/_authenticated/labs.proposals.$id'
import { Route as AuthenticatedLabsProjectsIdRouteImport } from './routes/_authenticated/labs.projects.$id'
import { Route as AuthenticatedLabsKnowledgeIdRouteImport } from './routes/_authenticated/labs.knowledge.$id'
import { Route as AuthenticatedLabsGoalsIdRouteImport } from './routes/_authenticated/labs.goals.$id'
import { Route as AuthenticatedLabsDocumentsIdRouteImport } from './routes/_authenticated/labs.documents.$id'
import { Route as AuthenticatedLabsDecisionsIdRouteImport } from './routes/_authenticated/labs.decisions.$id'
import { Route as AuthenticatedLabsCommitmentsIdRouteImport } from './routes/_authenticated/labs.commitments.$id'
import { Route as ApiPublicOauthMetaDeauthorizeRouteImport } from './routes/api/public/oauth/meta/deauthorize'
import { Route as ApiPublicOauthMetaDataDeletionRouteImport } from './routes/api/public/oauth/meta/data-deletion'
import { Route as ApiPublicOauthMetaCallbackRouteImport } from './routes/api/public/oauth/meta/callback'
import { Route as ApiPublicOauthMetaAuthorizeRouteImport } from './routes/api/public/oauth/meta/authorize'
import { Route as ApiPublicMediaMetaDeliveryTokenRouteImport } from './routes/api/public/media/meta-delivery.$token'
import { Route as AuthenticatedSamContentEditorIdRouteImport } from './routes/_authenticated/sam.content.editor.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalTokenRoute = ProposalTokenRouteImport.update({
  id: '/proposal/$token',
  path: '/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVenturesRoute = AuthenticatedVenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentOpsRoute = AuthenticatedContentOpsRouteImport.update({
  id: '/content-ops',
  path: '/content-ops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountabilityRoute =
  AuthenticatedAccountabilityRouteImport.update({
    id: '/accountability',
    path: '/accountability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamIndexRoute = AuthenticatedSamIndexRouteImport.update({
  id: '/sam/',
  path: '/sam/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabsIndexRoute = AuthenticatedLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsFounderActivationRoute =
  AuthenticatedSettingsFounderActivationRouteImport.update({
    id: '/founder-activation',
    path: '/founder-activation',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSamMemoryRoute = AuthenticatedSamMemoryRouteImport.update({
  id: '/sam/memory',
  path: '/sam/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSamIntegrationsRoute =
  AuthenticatedSamIntegrationsRouteImport.update({
    id: '/sam/integrations',
    path: '/sam/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamControlRoute = AuthenticatedSamControlRouteImport.update({
  id: '/sam/control',
  path: '/sam/control',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSamContentRoute = AuthenticatedSamContentRouteImport.update({
  id: '/sam/content',
  path: '/sam/content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabsVenturesRoute =
  AuthenticatedLabsVenturesRouteImport.update({
    id: '/labs/ventures',
    path: '/labs/ventures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsRevenueRoute =
  AuthenticatedLabsRevenueRouteImport.update({
    id: '/labs/revenue',
    path: '/labs/revenue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsProjectsRoute =
  AuthenticatedLabsProjectsRouteImport.update({
    id: '/labs/projects',
    path: '/labs/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsOperatorRoute =
  AuthenticatedLabsOperatorRouteImport.update({
    id: '/labs/operator',
    path: '/labs/operator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsMissionControlRoute =
  AuthenticatedLabsMissionControlRouteImport.update({
    id: '/labs/mission-control',
    path: '/labs/mission-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsKnowledgeRoute =
  AuthenticatedLabsKnowledgeRouteImport.update({
    id: '/labs/knowledge',
    path: '/labs/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsGoalsRoute = AuthenticatedLabsGoalsRouteImport.update({
  id: '/labs/goals',
  path: '/labs/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabsDocumentsRoute =
  AuthenticatedLabsDocumentsRouteImport.update({
    id: '/labs/documents',
    path: '/labs/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsDecisionsRoute =
  AuthenticatedLabsDecisionsRouteImport.update({
    id: '/labs/decisions',
    path: '/labs/decisions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsBillingRoute =
  AuthenticatedLabsBillingRouteImport.update({
    id: '/labs/billing',
    path: '/labs/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsAccountabilityRoute =
  AuthenticatedLabsAccountabilityRouteImport.update({
    id: '/labs/accountability',
    path: '/labs/accountability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsProposalsIndexRoute =
  AuthenticatedLabsProposalsIndexRouteImport.update({
    id: '/labs/proposals/',
    path: '/labs/proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProposalsViewRoute = ApiPublicProposalsViewRouteImport.update({
  id: '/api/public/proposals/view',
  path: '/api/public/proposals/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProposalsPdfRoute = ApiPublicProposalsPdfRouteImport.update({
  id: '/api/public/proposals/pdf',
  path: '/api/public/proposals/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProposalsDeclineRoute =
  ApiPublicProposalsDeclineRouteImport.update({
    id: '/api/public/proposals/decline',
    path: '/api/public/proposals/decline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProposalsAcceptRoute =
  ApiPublicProposalsAcceptRouteImport.update({
    id: '/api/public/proposals/accept',
    path: '/api/public/proposals/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationTickRoute = ApiPublicAutomationTickRouteImport.update({
  id: '/api/public/automation/tick',
  path: '/api/public/automation/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutomationSchedulerRoute =
  ApiPublicAutomationSchedulerRouteImport.update({
    id: '/api/public/automation/scheduler',
    path: '/api/public/automation/scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsIntegrationsNewRoute =
  AuthenticatedSettingsIntegrationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSettingsIntegrationsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsConnectionIdRoute =
  AuthenticatedSettingsIntegrationsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => AuthenticatedSettingsIntegrationsRoute,
  } as any)
const AuthenticatedSamMissionsIdRoute =
  AuthenticatedSamMissionsIdRouteImport.update({
    id: '/sam/missions/$id',
    path: '/sam/missions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamIntegrationsWebhooksRoute =
  AuthenticatedSamIntegrationsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedSamIntegrationsRoute,
  } as any)
const AuthenticatedSamIntegrationsRestEndpointsRoute =
  AuthenticatedSamIntegrationsRestEndpointsRouteImport.update({
    id: '/rest-endpoints',
    path: '/rest-endpoints',
    getParentRoute: () => AuthenticatedSamIntegrationsRoute,
  } as any)
const AuthenticatedSamContentLibraryRoute =
  AuthenticatedSamContentLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedSamContentRoute,
  } as any)
const AuthenticatedSamContentCalendarRoute =
  AuthenticatedSamContentCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedSamContentRoute,
  } as any)
const AuthenticatedLabsVenturesIdRoute =
  AuthenticatedLabsVenturesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLabsVenturesRoute,
  } as any)
const AuthenticatedLabsProposalsIdRoute =
  AuthenticatedLabsProposalsIdRouteImport.update({
    id: '/labs/proposals/$id',
    path: '/labs/proposals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsProjectsIdRoute =
  AuthenticatedLabsProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLabsProjectsRoute,
  } as any)
const AuthenticatedLabsKnowledgeIdRoute =
  AuthenticatedLabsKnowledgeIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLabsKnowledgeRoute,
  } as any)
const AuthenticatedLabsGoalsIdRoute =
  AuthenticatedLabsGoalsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLabsGoalsRoute,
  } as any)
const AuthenticatedLabsDocumentsIdRoute =
  AuthenticatedLabsDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLabsDocumentsRoute,
  } as any)
const AuthenticatedLabsDecisionsIdRoute =
  AuthenticatedLabsDecisionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLabsDecisionsRoute,
  } as any)
const AuthenticatedLabsCommitmentsIdRoute =
  AuthenticatedLabsCommitmentsIdRouteImport.update({
    id: '/labs/commitments/$id',
    path: '/labs/commitments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicOauthMetaDeauthorizeRoute =
  ApiPublicOauthMetaDeauthorizeRouteImport.update({
    id: '/api/public/oauth/meta/deauthorize',
    path: '/api/public/oauth/meta/deauthorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthMetaDataDeletionRoute =
  ApiPublicOauthMetaDataDeletionRouteImport.update({
    id: '/api/public/oauth/meta/data-deletion',
    path: '/api/public/oauth/meta/data-deletion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthMetaCallbackRoute =
  ApiPublicOauthMetaCallbackRouteImport.update({
    id: '/api/public/oauth/meta/callback',
    path: '/api/public/oauth/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthMetaAuthorizeRoute =
  ApiPublicOauthMetaAuthorizeRouteImport.update({
    id: '/api/public/oauth/meta/authorize',
    path: '/api/public/oauth/meta/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaMetaDeliveryTokenRoute =
  ApiPublicMediaMetaDeliveryTokenRouteImport.update({
    id: '/api/public/media/meta-delivery/$token',
    path: '/api/public/media/meta-delivery/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSamContentEditorIdRoute =
  AuthenticatedSamContentEditorIdRouteImport.update({
    id: '/editor/$id',
    path: '/editor/$id',
    getParentRoute: () => AuthenticatedSamContentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/accountability': typeof AuthenticatedAccountabilityRoute
  '/content-ops': typeof AuthenticatedContentOpsRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/ventures': typeof AuthenticatedVenturesRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/labs/accountability': typeof AuthenticatedLabsAccountabilityRoute
  '/labs/billing': typeof AuthenticatedLabsBillingRoute
  '/labs/decisions': typeof AuthenticatedLabsDecisionsRouteWithChildren
  '/labs/documents': typeof AuthenticatedLabsDocumentsRouteWithChildren
  '/labs/goals': typeof AuthenticatedLabsGoalsRouteWithChildren
  '/labs/knowledge': typeof AuthenticatedLabsKnowledgeRouteWithChildren
  '/labs/mission-control': typeof AuthenticatedLabsMissionControlRoute
  '/labs/operator': typeof AuthenticatedLabsOperatorRoute
  '/labs/projects': typeof AuthenticatedLabsProjectsRouteWithChildren
  '/labs/revenue': typeof AuthenticatedLabsRevenueRoute
  '/labs/ventures': typeof AuthenticatedLabsVenturesRouteWithChildren
  '/sam/content': typeof AuthenticatedSamContentRouteWithChildren
  '/sam/control': typeof AuthenticatedSamControlRoute
  '/sam/integrations': typeof AuthenticatedSamIntegrationsRouteWithChildren
  '/sam/memory': typeof AuthenticatedSamMemoryRoute
  '/settings/founder-activation': typeof AuthenticatedSettingsFounderActivationRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRouteWithChildren
  '/labs/': typeof AuthenticatedLabsIndexRoute
  '/sam/': typeof AuthenticatedSamIndexRoute
  '/labs/commitments/$id': typeof AuthenticatedLabsCommitmentsIdRoute
  '/labs/decisions/$id': typeof AuthenticatedLabsDecisionsIdRoute
  '/labs/documents/$id': typeof AuthenticatedLabsDocumentsIdRoute
  '/labs/goals/$id': typeof AuthenticatedLabsGoalsIdRoute
  '/labs/knowledge/$id': typeof AuthenticatedLabsKnowledgeIdRoute
  '/labs/projects/$id': typeof AuthenticatedLabsProjectsIdRoute
  '/labs/proposals/$id': typeof AuthenticatedLabsProposalsIdRoute
  '/labs/ventures/$id': typeof AuthenticatedLabsVenturesIdRoute
  '/sam/content/calendar': typeof AuthenticatedSamContentCalendarRoute
  '/sam/content/library': typeof AuthenticatedSamContentLibraryRoute
  '/sam/integrations/rest-endpoints': typeof AuthenticatedSamIntegrationsRestEndpointsRoute
  '/sam/integrations/webhooks': typeof AuthenticatedSamIntegrationsWebhooksRoute
  '/sam/missions/$id': typeof AuthenticatedSamMissionsIdRoute
  '/settings/integrations/$connectionId': typeof AuthenticatedSettingsIntegrationsConnectionIdRoute
  '/settings/integrations/new': typeof AuthenticatedSettingsIntegrationsNewRoute
  '/api/public/automation/scheduler': typeof ApiPublicAutomationSchedulerRoute
  '/api/public/automation/tick': typeof ApiPublicAutomationTickRoute
  '/api/public/proposals/accept': typeof ApiPublicProposalsAcceptRoute
  '/api/public/proposals/decline': typeof ApiPublicProposalsDeclineRoute
  '/api/public/proposals/pdf': typeof ApiPublicProposalsPdfRoute
  '/api/public/proposals/view': typeof ApiPublicProposalsViewRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/labs/proposals/': typeof AuthenticatedLabsProposalsIndexRoute
  '/sam/content/editor/$id': typeof AuthenticatedSamContentEditorIdRoute
  '/api/public/media/meta-delivery/$token': typeof ApiPublicMediaMetaDeliveryTokenRoute
  '/api/public/oauth/meta/authorize': typeof ApiPublicOauthMetaAuthorizeRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/meta/data-deletion': typeof ApiPublicOauthMetaDataDeletionRoute
  '/api/public/oauth/meta/deauthorize': typeof ApiPublicOauthMetaDeauthorizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/accountability': typeof AuthenticatedAccountabilityRoute
  '/content-ops': typeof AuthenticatedContentOpsRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/ventures': typeof AuthenticatedVenturesRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/labs/accountability': typeof AuthenticatedLabsAccountabilityRoute
  '/labs/billing': typeof AuthenticatedLabsBillingRoute
  '/labs/decisions': typeof AuthenticatedLabsDecisionsRouteWithChildren
  '/labs/documents': typeof AuthenticatedLabsDocumentsRouteWithChildren
  '/labs/goals': typeof AuthenticatedLabsGoalsRouteWithChildren
  '/labs/knowledge': typeof AuthenticatedLabsKnowledgeRouteWithChildren
  '/labs/mission-control': typeof AuthenticatedLabsMissionControlRoute
  '/labs/operator': typeof AuthenticatedLabsOperatorRoute
  '/labs/projects': typeof AuthenticatedLabsProjectsRouteWithChildren
  '/labs/revenue': typeof AuthenticatedLabsRevenueRoute
  '/labs/ventures': typeof AuthenticatedLabsVenturesRouteWithChildren
  '/sam/content': typeof AuthenticatedSamContentRouteWithChildren
  '/sam/control': typeof AuthenticatedSamControlRoute
  '/sam/integrations': typeof AuthenticatedSamIntegrationsRouteWithChildren
  '/sam/memory': typeof AuthenticatedSamMemoryRoute
  '/settings/founder-activation': typeof AuthenticatedSettingsFounderActivationRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRouteWithChildren
  '/labs': typeof AuthenticatedLabsIndexRoute
  '/sam': typeof AuthenticatedSamIndexRoute
  '/labs/commitments/$id': typeof AuthenticatedLabsCommitmentsIdRoute
  '/labs/decisions/$id': typeof AuthenticatedLabsDecisionsIdRoute
  '/labs/documents/$id': typeof AuthenticatedLabsDocumentsIdRoute
  '/labs/goals/$id': typeof AuthenticatedLabsGoalsIdRoute
  '/labs/knowledge/$id': typeof AuthenticatedLabsKnowledgeIdRoute
  '/labs/projects/$id': typeof AuthenticatedLabsProjectsIdRoute
  '/labs/proposals/$id': typeof AuthenticatedLabsProposalsIdRoute
  '/labs/ventures/$id': typeof AuthenticatedLabsVenturesIdRoute
  '/sam/content/calendar': typeof AuthenticatedSamContentCalendarRoute
  '/sam/content/library': typeof AuthenticatedSamContentLibraryRoute
  '/sam/integrations/rest-endpoints': typeof AuthenticatedSamIntegrationsRestEndpointsRoute
  '/sam/integrations/webhooks': typeof AuthenticatedSamIntegrationsWebhooksRoute
  '/sam/missions/$id': typeof AuthenticatedSamMissionsIdRoute
  '/settings/integrations/$connectionId': typeof AuthenticatedSettingsIntegrationsConnectionIdRoute
  '/settings/integrations/new': typeof AuthenticatedSettingsIntegrationsNewRoute
  '/api/public/automation/scheduler': typeof ApiPublicAutomationSchedulerRoute
  '/api/public/automation/tick': typeof ApiPublicAutomationTickRoute
  '/api/public/proposals/accept': typeof ApiPublicProposalsAcceptRoute
  '/api/public/proposals/decline': typeof ApiPublicProposalsDeclineRoute
  '/api/public/proposals/pdf': typeof ApiPublicProposalsPdfRoute
  '/api/public/proposals/view': typeof ApiPublicProposalsViewRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/labs/proposals': typeof AuthenticatedLabsProposalsIndexRoute
  '/sam/content/editor/$id': typeof AuthenticatedSamContentEditorIdRoute
  '/api/public/media/meta-delivery/$token': typeof ApiPublicMediaMetaDeliveryTokenRoute
  '/api/public/oauth/meta/authorize': typeof ApiPublicOauthMetaAuthorizeRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/meta/data-deletion': typeof ApiPublicOauthMetaDataDeletionRoute
  '/api/public/oauth/meta/deauthorize': typeof ApiPublicOauthMetaDeauthorizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/accountability': typeof AuthenticatedAccountabilityRoute
  '/_authenticated/content-ops': typeof AuthenticatedContentOpsRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/ventures': typeof AuthenticatedVenturesRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/_authenticated/labs/accountability': typeof AuthenticatedLabsAccountabilityRoute
  '/_authenticated/labs/billing': typeof AuthenticatedLabsBillingRoute
  '/_authenticated/labs/decisions': typeof AuthenticatedLabsDecisionsRouteWithChildren
  '/_authenticated/labs/documents': typeof AuthenticatedLabsDocumentsRouteWithChildren
  '/_authenticated/labs/goals': typeof AuthenticatedLabsGoalsRouteWithChildren
  '/_authenticated/labs/knowledge': typeof AuthenticatedLabsKnowledgeRouteWithChildren
  '/_authenticated/labs/mission-control': typeof AuthenticatedLabsMissionControlRoute
  '/_authenticated/labs/operator': typeof AuthenticatedLabsOperatorRoute
  '/_authenticated/labs/projects': typeof AuthenticatedLabsProjectsRouteWithChildren
  '/_authenticated/labs/revenue': typeof AuthenticatedLabsRevenueRoute
  '/_authenticated/labs/ventures': typeof AuthenticatedLabsVenturesRouteWithChildren
  '/_authenticated/sam/content': typeof AuthenticatedSamContentRouteWithChildren
  '/_authenticated/sam/control': typeof AuthenticatedSamControlRoute
  '/_authenticated/sam/integrations': typeof AuthenticatedSamIntegrationsRouteWithChildren
  '/_authenticated/sam/memory': typeof AuthenticatedSamMemoryRoute
  '/_authenticated/settings/founder-activation': typeof AuthenticatedSettingsFounderActivationRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRouteWithChildren
  '/_authenticated/labs/': typeof AuthenticatedLabsIndexRoute
  '/_authenticated/sam/': typeof AuthenticatedSamIndexRoute
  '/_authenticated/labs/commitments/$id': typeof AuthenticatedLabsCommitmentsIdRoute
  '/_authenticated/labs/decisions/$id': typeof AuthenticatedLabsDecisionsIdRoute
  '/_authenticated/labs/documents/$id': typeof AuthenticatedLabsDocumentsIdRoute
  '/_authenticated/labs/goals/$id': typeof AuthenticatedLabsGoalsIdRoute
  '/_authenticated/labs/knowledge/$id': typeof AuthenticatedLabsKnowledgeIdRoute
  '/_authenticated/labs/projects/$id': typeof AuthenticatedLabsProjectsIdRoute
  '/_authenticated/labs/proposals/$id': typeof AuthenticatedLabsProposalsIdRoute
  '/_authenticated/labs/ventures/$id': typeof AuthenticatedLabsVenturesIdRoute
  '/_authenticated/sam/content/calendar': typeof AuthenticatedSamContentCalendarRoute
  '/_authenticated/sam/content/library': typeof AuthenticatedSamContentLibraryRoute
  '/_authenticated/sam/integrations/rest-endpoints': typeof AuthenticatedSamIntegrationsRestEndpointsRoute
  '/_authenticated/sam/integrations/webhooks': typeof AuthenticatedSamIntegrationsWebhooksRoute
  '/_authenticated/sam/missions/$id': typeof AuthenticatedSamMissionsIdRoute
  '/_authenticated/settings/integrations/$connectionId': typeof AuthenticatedSettingsIntegrationsConnectionIdRoute
  '/_authenticated/settings/integrations/new': typeof AuthenticatedSettingsIntegrationsNewRoute
  '/api/public/automation/scheduler': typeof ApiPublicAutomationSchedulerRoute
  '/api/public/automation/tick': typeof ApiPublicAutomationTickRoute
  '/api/public/proposals/accept': typeof ApiPublicProposalsAcceptRoute
  '/api/public/proposals/decline': typeof ApiPublicProposalsDeclineRoute
  '/api/public/proposals/pdf': typeof ApiPublicProposalsPdfRoute
  '/api/public/proposals/view': typeof ApiPublicProposalsViewRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/labs/proposals/': typeof AuthenticatedLabsProposalsIndexRoute
  '/_authenticated/sam/content/editor/$id': typeof AuthenticatedSamContentEditorIdRoute
  '/api/public/media/meta-delivery/$token': typeof ApiPublicMediaMetaDeliveryTokenRoute
  '/api/public/oauth/meta/authorize': typeof ApiPublicOauthMetaAuthorizeRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/meta/data-deletion': typeof ApiPublicOauthMetaDataDeletionRoute
  '/api/public/oauth/meta/deauthorize': typeof ApiPublicOauthMetaDeauthorizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/accountability'
    | '/content-ops'
    | '/decisions'
    | '/documents'
    | '/goals'
    | '/integrations'
    | '/knowledge'
    | '/operator'
    | '/projects'
    | '/revenue'
    | '/settings'
    | '/ventures'
    | '/api/generate-image'
    | '/auth/forgot'
    | '/auth/reset'
    | '/proposal/$token'
    | '/labs/accountability'
    | '/labs/billing'
    | '/labs/decisions'
    | '/labs/documents'
    | '/labs/goals'
    | '/labs/knowledge'
    | '/labs/mission-control'
    | '/labs/operator'
    | '/labs/projects'
    | '/labs/revenue'
    | '/labs/ventures'
    | '/sam/content'
    | '/sam/control'
    | '/sam/integrations'
    | '/sam/memory'
    | '/settings/founder-activation'
    | '/settings/integrations'
    | '/labs/'
    | '/sam/'
    | '/labs/commitments/$id'
    | '/labs/decisions/$id'
    | '/labs/documents/$id'
    | '/labs/goals/$id'
    | '/labs/knowledge/$id'
    | '/labs/projects/$id'
    | '/labs/proposals/$id'
    | '/labs/ventures/$id'
    | '/sam/content/calendar'
    | '/sam/content/library'
    | '/sam/integrations/rest-endpoints'
    | '/sam/integrations/webhooks'
    | '/sam/missions/$id'
    | '/settings/integrations/$connectionId'
    | '/settings/integrations/new'
    | '/api/public/automation/scheduler'
    | '/api/public/automation/tick'
    | '/api/public/proposals/accept'
    | '/api/public/proposals/decline'
    | '/api/public/proposals/pdf'
    | '/api/public/proposals/view'
    | '/api/public/stripe/webhook'
    | '/labs/proposals/'
    | '/sam/content/editor/$id'
    | '/api/public/media/meta-delivery/$token'
    | '/api/public/oauth/meta/authorize'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/meta/data-deletion'
    | '/api/public/oauth/meta/deauthorize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/accountability'
    | '/content-ops'
    | '/decisions'
    | '/documents'
    | '/goals'
    | '/integrations'
    | '/knowledge'
    | '/operator'
    | '/projects'
    | '/revenue'
    | '/settings'
    | '/ventures'
    | '/api/generate-image'
    | '/auth/forgot'
    | '/auth/reset'
    | '/proposal/$token'
    | '/labs/accountability'
    | '/labs/billing'
    | '/labs/decisions'
    | '/labs/documents'
    | '/labs/goals'
    | '/labs/knowledge'
    | '/labs/mission-control'
    | '/labs/operator'
    | '/labs/projects'
    | '/labs/revenue'
    | '/labs/ventures'
    | '/sam/content'
    | '/sam/control'
    | '/sam/integrations'
    | '/sam/memory'
    | '/settings/founder-activation'
    | '/settings/integrations'
    | '/labs'
    | '/sam'
    | '/labs/commitments/$id'
    | '/labs/decisions/$id'
    | '/labs/documents/$id'
    | '/labs/goals/$id'
    | '/labs/knowledge/$id'
    | '/labs/projects/$id'
    | '/labs/proposals/$id'
    | '/labs/ventures/$id'
    | '/sam/content/calendar'
    | '/sam/content/library'
    | '/sam/integrations/rest-endpoints'
    | '/sam/integrations/webhooks'
    | '/sam/missions/$id'
    | '/settings/integrations/$connectionId'
    | '/settings/integrations/new'
    | '/api/public/automation/scheduler'
    | '/api/public/automation/tick'
    | '/api/public/proposals/accept'
    | '/api/public/proposals/decline'
    | '/api/public/proposals/pdf'
    | '/api/public/proposals/view'
    | '/api/public/stripe/webhook'
    | '/labs/proposals'
    | '/sam/content/editor/$id'
    | '/api/public/media/meta-delivery/$token'
    | '/api/public/oauth/meta/authorize'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/meta/data-deletion'
    | '/api/public/oauth/meta/deauthorize'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/accountability'
    | '/_authenticated/content-ops'
    | '/_authenticated/decisions'
    | '/_authenticated/documents'
    | '/_authenticated/goals'
    | '/_authenticated/integrations'
    | '/_authenticated/knowledge'
    | '/_authenticated/operator'
    | '/_authenticated/projects'
    | '/_authenticated/revenue'
    | '/_authenticated/settings'
    | '/_authenticated/ventures'
    | '/api/generate-image'
    | '/auth/forgot'
    | '/auth/reset'
    | '/proposal/$token'
    | '/_authenticated/labs/accountability'
    | '/_authenticated/labs/billing'
    | '/_authenticated/labs/decisions'
    | '/_authenticated/labs/documents'
    | '/_authenticated/labs/goals'
    | '/_authenticated/labs/knowledge'
    | '/_authenticated/labs/mission-control'
    | '/_authenticated/labs/operator'
    | '/_authenticated/labs/projects'
    | '/_authenticated/labs/revenue'
    | '/_authenticated/labs/ventures'
    | '/_authenticated/sam/content'
    | '/_authenticated/sam/control'
    | '/_authenticated/sam/integrations'
    | '/_authenticated/sam/memory'
    | '/_authenticated/settings/founder-activation'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/labs/'
    | '/_authenticated/sam/'
    | '/_authenticated/labs/commitments/$id'
    | '/_authenticated/labs/decisions/$id'
    | '/_authenticated/labs/documents/$id'
    | '/_authenticated/labs/goals/$id'
    | '/_authenticated/labs/knowledge/$id'
    | '/_authenticated/labs/projects/$id'
    | '/_authenticated/labs/proposals/$id'
    | '/_authenticated/labs/ventures/$id'
    | '/_authenticated/sam/content/calendar'
    | '/_authenticated/sam/content/library'
    | '/_authenticated/sam/integrations/rest-endpoints'
    | '/_authenticated/sam/integrations/webhooks'
    | '/_authenticated/sam/missions/$id'
    | '/_authenticated/settings/integrations/$connectionId'
    | '/_authenticated/settings/integrations/new'
    | '/api/public/automation/scheduler'
    | '/api/public/automation/tick'
    | '/api/public/proposals/accept'
    | '/api/public/proposals/decline'
    | '/api/public/proposals/pdf'
    | '/api/public/proposals/view'
    | '/api/public/stripe/webhook'
    | '/_authenticated/labs/proposals/'
    | '/_authenticated/sam/content/editor/$id'
    | '/api/public/media/meta-delivery/$token'
    | '/api/public/oauth/meta/authorize'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/meta/data-deletion'
    | '/api/public/oauth/meta/deauthorize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ProposalTokenRoute: typeof ProposalTokenRoute
  ApiPublicAutomationSchedulerRoute: typeof ApiPublicAutomationSchedulerRoute
  ApiPublicAutomationTickRoute: typeof ApiPublicAutomationTickRoute
  ApiPublicProposalsAcceptRoute: typeof ApiPublicProposalsAcceptRoute
  ApiPublicProposalsDeclineRoute: typeof ApiPublicProposalsDeclineRoute
  ApiPublicProposalsPdfRoute: typeof ApiPublicProposalsPdfRoute
  ApiPublicProposalsViewRoute: typeof ApiPublicProposalsViewRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicMediaMetaDeliveryTokenRoute: typeof ApiPublicMediaMetaDeliveryTokenRoute
  ApiPublicOauthMetaAuthorizeRoute: typeof ApiPublicOauthMetaAuthorizeRoute
  ApiPublicOauthMetaCallbackRoute: typeof ApiPublicOauthMetaCallbackRoute
  ApiPublicOauthMetaDataDeletionRoute: typeof ApiPublicOauthMetaDataDeletionRoute
  ApiPublicOauthMetaDeauthorizeRoute: typeof ApiPublicOauthMetaDeauthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$token': {
      id: '/proposal/$token'
      path: '/proposal/$token'
      fullPath: '/proposal/$token'
      preLoaderRoute: typeof ProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventures': {
      id: '/_authenticated/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof AuthenticatedVenturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content-ops': {
      id: '/_authenticated/content-ops'
      path: '/content-ops'
      fullPath: '/content-ops'
      preLoaderRoute: typeof AuthenticatedContentOpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accountability': {
      id: '/_authenticated/accountability'
      path: '/accountability'
      fullPath: '/accountability'
      preLoaderRoute: typeof AuthenticatedAccountabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sam/': {
      id: '/_authenticated/sam/'
      path: '/sam'
      fullPath: '/sam/'
      preLoaderRoute: typeof AuthenticatedSamIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/': {
      id: '/_authenticated/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof AuthenticatedLabsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/founder-activation': {
      id: '/_authenticated/settings/founder-activation'
      path: '/founder-activation'
      fullPath: '/settings/founder-activation'
      preLoaderRoute: typeof AuthenticatedSettingsFounderActivationRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/sam/memory': {
      id: '/_authenticated/sam/memory'
      path: '/sam/memory'
      fullPath: '/sam/memory'
      preLoaderRoute: typeof AuthenticatedSamMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sam/integrations': {
      id: '/_authenticated/sam/integrations'
      path: '/sam/integrations'
      fullPath: '/sam/integrations'
      preLoaderRoute: typeof AuthenticatedSamIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sam/control': {
      id: '/_authenticated/sam/control'
      path: '/sam/control'
      fullPath: '/sam/control'
      preLoaderRoute: typeof AuthenticatedSamControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sam/content': {
      id: '/_authenticated/sam/content'
      path: '/sam/content'
      fullPath: '/sam/content'
      preLoaderRoute: typeof AuthenticatedSamContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/ventures': {
      id: '/_authenticated/labs/ventures'
      path: '/labs/ventures'
      fullPath: '/labs/ventures'
      preLoaderRoute: typeof AuthenticatedLabsVenturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/revenue': {
      id: '/_authenticated/labs/revenue'
      path: '/labs/revenue'
      fullPath: '/labs/revenue'
      preLoaderRoute: typeof AuthenticatedLabsRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/projects': {
      id: '/_authenticated/labs/projects'
      path: '/labs/projects'
      fullPath: '/labs/projects'
      preLoaderRoute: typeof AuthenticatedLabsProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/operator': {
      id: '/_authenticated/labs/operator'
      path: '/labs/operator'
      fullPath: '/labs/operator'
      preLoaderRoute: typeof AuthenticatedLabsOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/mission-control': {
      id: '/_authenticated/labs/mission-control'
      path: '/labs/mission-control'
      fullPath: '/labs/mission-control'
      preLoaderRoute: typeof AuthenticatedLabsMissionControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/knowledge': {
      id: '/_authenticated/labs/knowledge'
      path: '/labs/knowledge'
      fullPath: '/labs/knowledge'
      preLoaderRoute: typeof AuthenticatedLabsKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/goals': {
      id: '/_authenticated/labs/goals'
      path: '/labs/goals'
      fullPath: '/labs/goals'
      preLoaderRoute: typeof AuthenticatedLabsGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/documents': {
      id: '/_authenticated/labs/documents'
      path: '/labs/documents'
      fullPath: '/labs/documents'
      preLoaderRoute: typeof AuthenticatedLabsDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/decisions': {
      id: '/_authenticated/labs/decisions'
      path: '/labs/decisions'
      fullPath: '/labs/decisions'
      preLoaderRoute: typeof AuthenticatedLabsDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/billing': {
      id: '/_authenticated/labs/billing'
      path: '/labs/billing'
      fullPath: '/labs/billing'
      preLoaderRoute: typeof AuthenticatedLabsBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/accountability': {
      id: '/_authenticated/labs/accountability'
      path: '/labs/accountability'
      fullPath: '/labs/accountability'
      preLoaderRoute: typeof AuthenticatedLabsAccountabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/proposals/': {
      id: '/_authenticated/labs/proposals/'
      path: '/labs/proposals'
      fullPath: '/labs/proposals/'
      preLoaderRoute: typeof AuthenticatedLabsProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposals/view': {
      id: '/api/public/proposals/view'
      path: '/api/public/proposals/view'
      fullPath: '/api/public/proposals/view'
      preLoaderRoute: typeof ApiPublicProposalsViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposals/pdf': {
      id: '/api/public/proposals/pdf'
      path: '/api/public/proposals/pdf'
      fullPath: '/api/public/proposals/pdf'
      preLoaderRoute: typeof ApiPublicProposalsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposals/decline': {
      id: '/api/public/proposals/decline'
      path: '/api/public/proposals/decline'
      fullPath: '/api/public/proposals/decline'
      preLoaderRoute: typeof ApiPublicProposalsDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposals/accept': {
      id: '/api/public/proposals/accept'
      path: '/api/public/proposals/accept'
      fullPath: '/api/public/proposals/accept'
      preLoaderRoute: typeof ApiPublicProposalsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/tick': {
      id: '/api/public/automation/tick'
      path: '/api/public/automation/tick'
      fullPath: '/api/public/automation/tick'
      preLoaderRoute: typeof ApiPublicAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation/scheduler': {
      id: '/api/public/automation/scheduler'
      path: '/api/public/automation/scheduler'
      fullPath: '/api/public/automation/scheduler'
      preLoaderRoute: typeof ApiPublicAutomationSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/integrations/new': {
      id: '/_authenticated/settings/integrations/new'
      path: '/new'
      fullPath: '/settings/integrations/new'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsNewRouteImport
      parentRoute: typeof AuthenticatedSettingsIntegrationsRoute
    }
    '/_authenticated/settings/integrations/$connectionId': {
      id: '/_authenticated/settings/integrations/$connectionId'
      path: '/$connectionId'
      fullPath: '/settings/integrations/$connectionId'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsConnectionIdRouteImport
      parentRoute: typeof AuthenticatedSettingsIntegrationsRoute
    }
    '/_authenticated/sam/missions/$id': {
      id: '/_authenticated/sam/missions/$id'
      path: '/sam/missions/$id'
      fullPath: '/sam/missions/$id'
      preLoaderRoute: typeof AuthenticatedSamMissionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sam/integrations/webhooks': {
      id: '/_authenticated/sam/integrations/webhooks'
      path: '/webhooks'
      fullPath: '/sam/integrations/webhooks'
      preLoaderRoute: typeof AuthenticatedSamIntegrationsWebhooksRouteImport
      parentRoute: typeof AuthenticatedSamIntegrationsRoute
    }
    '/_authenticated/sam/integrations/rest-endpoints': {
      id: '/_authenticated/sam/integrations/rest-endpoints'
      path: '/rest-endpoints'
      fullPath: '/sam/integrations/rest-endpoints'
      preLoaderRoute: typeof AuthenticatedSamIntegrationsRestEndpointsRouteImport
      parentRoute: typeof AuthenticatedSamIntegrationsRoute
    }
    '/_authenticated/sam/content/library': {
      id: '/_authenticated/sam/content/library'
      path: '/library'
      fullPath: '/sam/content/library'
      preLoaderRoute: typeof AuthenticatedSamContentLibraryRouteImport
      parentRoute: typeof AuthenticatedSamContentRoute
    }
    '/_authenticated/sam/content/calendar': {
      id: '/_authenticated/sam/content/calendar'
      path: '/calendar'
      fullPath: '/sam/content/calendar'
      preLoaderRoute: typeof AuthenticatedSamContentCalendarRouteImport
      parentRoute: typeof AuthenticatedSamContentRoute
    }
    '/_authenticated/labs/ventures/$id': {
      id: '/_authenticated/labs/ventures/$id'
      path: '/$id'
      fullPath: '/labs/ventures/$id'
      preLoaderRoute: typeof AuthenticatedLabsVenturesIdRouteImport
      parentRoute: typeof AuthenticatedLabsVenturesRoute
    }
    '/_authenticated/labs/proposals/$id': {
      id: '/_authenticated/labs/proposals/$id'
      path: '/labs/proposals/$id'
      fullPath: '/labs/proposals/$id'
      preLoaderRoute: typeof AuthenticatedLabsProposalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/projects/$id': {
      id: '/_authenticated/labs/projects/$id'
      path: '/$id'
      fullPath: '/labs/projects/$id'
      preLoaderRoute: typeof AuthenticatedLabsProjectsIdRouteImport
      parentRoute: typeof AuthenticatedLabsProjectsRoute
    }
    '/_authenticated/labs/knowledge/$id': {
      id: '/_authenticated/labs/knowledge/$id'
      path: '/$id'
      fullPath: '/labs/knowledge/$id'
      preLoaderRoute: typeof AuthenticatedLabsKnowledgeIdRouteImport
      parentRoute: typeof AuthenticatedLabsKnowledgeRoute
    }
    '/_authenticated/labs/goals/$id': {
      id: '/_authenticated/labs/goals/$id'
      path: '/$id'
      fullPath: '/labs/goals/$id'
      preLoaderRoute: typeof AuthenticatedLabsGoalsIdRouteImport
      parentRoute: typeof AuthenticatedLabsGoalsRoute
    }
    '/_authenticated/labs/documents/$id': {
      id: '/_authenticated/labs/documents/$id'
      path: '/$id'
      fullPath: '/labs/documents/$id'
      preLoaderRoute: typeof AuthenticatedLabsDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedLabsDocumentsRoute
    }
    '/_authenticated/labs/decisions/$id': {
      id: '/_authenticated/labs/decisions/$id'
      path: '/$id'
      fullPath: '/labs/decisions/$id'
      preLoaderRoute: typeof AuthenticatedLabsDecisionsIdRouteImport
      parentRoute: typeof AuthenticatedLabsDecisionsRoute
    }
    '/_authenticated/labs/commitments/$id': {
      id: '/_authenticated/labs/commitments/$id'
      path: '/labs/commitments/$id'
      fullPath: '/labs/commitments/$id'
      preLoaderRoute: typeof AuthenticatedLabsCommitmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/oauth/meta/deauthorize': {
      id: '/api/public/oauth/meta/deauthorize'
      path: '/api/public/oauth/meta/deauthorize'
      fullPath: '/api/public/oauth/meta/deauthorize'
      preLoaderRoute: typeof ApiPublicOauthMetaDeauthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta/data-deletion': {
      id: '/api/public/oauth/meta/data-deletion'
      path: '/api/public/oauth/meta/data-deletion'
      fullPath: '/api/public/oauth/meta/data-deletion'
      preLoaderRoute: typeof ApiPublicOauthMetaDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta/callback': {
      id: '/api/public/oauth/meta/callback'
      path: '/api/public/oauth/meta/callback'
      fullPath: '/api/public/oauth/meta/callback'
      preLoaderRoute: typeof ApiPublicOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta/authorize': {
      id: '/api/public/oauth/meta/authorize'
      path: '/api/public/oauth/meta/authorize'
      fullPath: '/api/public/oauth/meta/authorize'
      preLoaderRoute: typeof ApiPublicOauthMetaAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/meta-delivery/$token': {
      id: '/api/public/media/meta-delivery/$token'
      path: '/api/public/media/meta-delivery/$token'
      fullPath: '/api/public/media/meta-delivery/$token'
      preLoaderRoute: typeof ApiPublicMediaMetaDeliveryTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sam/content/editor/$id': {
      id: '/_authenticated/sam/content/editor/$id'
      path: '/editor/$id'
      fullPath: '/sam/content/editor/$id'
      preLoaderRoute: typeof AuthenticatedSamContentEditorIdRouteImport
      parentRoute: typeof AuthenticatedSamContentRoute
    }
  }
}

interface AuthenticatedSettingsIntegrationsRouteChildren {
  AuthenticatedSettingsIntegrationsConnectionIdRoute: typeof AuthenticatedSettingsIntegrationsConnectionIdRoute
  AuthenticatedSettingsIntegrationsNewRoute: typeof AuthenticatedSettingsIntegrationsNewRoute
}

const AuthenticatedSettingsIntegrationsRouteChildren: AuthenticatedSettingsIntegrationsRouteChildren =
  {
    AuthenticatedSettingsIntegrationsConnectionIdRoute:
      AuthenticatedSettingsIntegrationsConnectionIdRoute,
    AuthenticatedSettingsIntegrationsNewRoute:
      AuthenticatedSettingsIntegrationsNewRoute,
  }

const AuthenticatedSettingsIntegrationsRouteWithChildren =
  AuthenticatedSettingsIntegrationsRoute._addFileChildren(
    AuthenticatedSettingsIntegrationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsFounderActivationRoute: typeof AuthenticatedSettingsFounderActivationRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRouteWithChildren
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsFounderActivationRoute:
    AuthenticatedSettingsFounderActivationRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRouteWithChildren,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedLabsDecisionsRouteChildren {
  AuthenticatedLabsDecisionsIdRoute: typeof AuthenticatedLabsDecisionsIdRoute
}

const AuthenticatedLabsDecisionsRouteChildren: AuthenticatedLabsDecisionsRouteChildren =
  {
    AuthenticatedLabsDecisionsIdRoute: AuthenticatedLabsDecisionsIdRoute,
  }

const AuthenticatedLabsDecisionsRouteWithChildren =
  AuthenticatedLabsDecisionsRoute._addFileChildren(
    AuthenticatedLabsDecisionsRouteChildren,
  )

interface AuthenticatedLabsDocumentsRouteChildren {
  AuthenticatedLabsDocumentsIdRoute: typeof AuthenticatedLabsDocumentsIdRoute
}

const AuthenticatedLabsDocumentsRouteChildren: AuthenticatedLabsDocumentsRouteChildren =
  {
    AuthenticatedLabsDocumentsIdRoute: AuthenticatedLabsDocumentsIdRoute,
  }

const AuthenticatedLabsDocumentsRouteWithChildren =
  AuthenticatedLabsDocumentsRoute._addFileChildren(
    AuthenticatedLabsDocumentsRouteChildren,
  )

interface AuthenticatedLabsGoalsRouteChildren {
  AuthenticatedLabsGoalsIdRoute: typeof AuthenticatedLabsGoalsIdRoute
}

const AuthenticatedLabsGoalsRouteChildren: AuthenticatedLabsGoalsRouteChildren =
  {
    AuthenticatedLabsGoalsIdRoute: AuthenticatedLabsGoalsIdRoute,
  }

const AuthenticatedLabsGoalsRouteWithChildren =
  AuthenticatedLabsGoalsRoute._addFileChildren(
    AuthenticatedLabsGoalsRouteChildren,
  )

interface AuthenticatedLabsKnowledgeRouteChildren {
  AuthenticatedLabsKnowledgeIdRoute: typeof AuthenticatedLabsKnowledgeIdRoute
}

const AuthenticatedLabsKnowledgeRouteChildren: AuthenticatedLabsKnowledgeRouteChildren =
  {
    AuthenticatedLabsKnowledgeIdRoute: AuthenticatedLabsKnowledgeIdRoute,
  }

const AuthenticatedLabsKnowledgeRouteWithChildren =
  AuthenticatedLabsKnowledgeRoute._addFileChildren(
    AuthenticatedLabsKnowledgeRouteChildren,
  )

interface AuthenticatedLabsProjectsRouteChildren {
  AuthenticatedLabsProjectsIdRoute: typeof AuthenticatedLabsProjectsIdRoute
}

const AuthenticatedLabsProjectsRouteChildren: AuthenticatedLabsProjectsRouteChildren =
  {
    AuthenticatedLabsProjectsIdRoute: AuthenticatedLabsProjectsIdRoute,
  }

const AuthenticatedLabsProjectsRouteWithChildren =
  AuthenticatedLabsProjectsRoute._addFileChildren(
    AuthenticatedLabsProjectsRouteChildren,
  )

interface AuthenticatedLabsVenturesRouteChildren {
  AuthenticatedLabsVenturesIdRoute: typeof AuthenticatedLabsVenturesIdRoute
}

const AuthenticatedLabsVenturesRouteChildren: AuthenticatedLabsVenturesRouteChildren =
  {
    AuthenticatedLabsVenturesIdRoute: AuthenticatedLabsVenturesIdRoute,
  }

const AuthenticatedLabsVenturesRouteWithChildren =
  AuthenticatedLabsVenturesRoute._addFileChildren(
    AuthenticatedLabsVenturesRouteChildren,
  )

interface AuthenticatedSamContentRouteChildren {
  AuthenticatedSamContentCalendarRoute: typeof AuthenticatedSamContentCalendarRoute
  AuthenticatedSamContentLibraryRoute: typeof AuthenticatedSamContentLibraryRoute
  AuthenticatedSamContentEditorIdRoute: typeof AuthenticatedSamContentEditorIdRoute
}

const AuthenticatedSamContentRouteChildren: AuthenticatedSamContentRouteChildren =
  {
    AuthenticatedSamContentCalendarRoute: AuthenticatedSamContentCalendarRoute,
    AuthenticatedSamContentLibraryRoute: AuthenticatedSamContentLibraryRoute,
    AuthenticatedSamContentEditorIdRoute: AuthenticatedSamContentEditorIdRoute,
  }

const AuthenticatedSamContentRouteWithChildren =
  AuthenticatedSamContentRoute._addFileChildren(
    AuthenticatedSamContentRouteChildren,
  )

interface AuthenticatedSamIntegrationsRouteChildren {
  AuthenticatedSamIntegrationsRestEndpointsRoute: typeof AuthenticatedSamIntegrationsRestEndpointsRoute
  AuthenticatedSamIntegrationsWebhooksRoute: typeof AuthenticatedSamIntegrationsWebhooksRoute
}

const AuthenticatedSamIntegrationsRouteChildren: AuthenticatedSamIntegrationsRouteChildren =
  {
    AuthenticatedSamIntegrationsRestEndpointsRoute:
      AuthenticatedSamIntegrationsRestEndpointsRoute,
    AuthenticatedSamIntegrationsWebhooksRoute:
      AuthenticatedSamIntegrationsWebhooksRoute,
  }

const AuthenticatedSamIntegrationsRouteWithChildren =
  AuthenticatedSamIntegrationsRoute._addFileChildren(
    AuthenticatedSamIntegrationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountabilityRoute: typeof AuthenticatedAccountabilityRoute
  AuthenticatedContentOpsRoute: typeof AuthenticatedContentOpsRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedVenturesRoute: typeof AuthenticatedVenturesRoute
  AuthenticatedLabsAccountabilityRoute: typeof AuthenticatedLabsAccountabilityRoute
  AuthenticatedLabsBillingRoute: typeof AuthenticatedLabsBillingRoute
  AuthenticatedLabsDecisionsRoute: typeof AuthenticatedLabsDecisionsRouteWithChildren
  AuthenticatedLabsDocumentsRoute: typeof AuthenticatedLabsDocumentsRouteWithChildren
  AuthenticatedLabsGoalsRoute: typeof AuthenticatedLabsGoalsRouteWithChildren
  AuthenticatedLabsKnowledgeRoute: typeof AuthenticatedLabsKnowledgeRouteWithChildren
  AuthenticatedLabsMissionControlRoute: typeof AuthenticatedLabsMissionControlRoute
  AuthenticatedLabsOperatorRoute: typeof AuthenticatedLabsOperatorRoute
  AuthenticatedLabsProjectsRoute: typeof AuthenticatedLabsProjectsRouteWithChildren
  AuthenticatedLabsRevenueRoute: typeof AuthenticatedLabsRevenueRoute
  AuthenticatedLabsVenturesRoute: typeof AuthenticatedLabsVenturesRouteWithChildren
  AuthenticatedSamContentRoute: typeof AuthenticatedSamContentRouteWithChildren
  AuthenticatedSamControlRoute: typeof AuthenticatedSamControlRoute
  AuthenticatedSamIntegrationsRoute: typeof AuthenticatedSamIntegrationsRouteWithChildren
  AuthenticatedSamMemoryRoute: typeof AuthenticatedSamMemoryRoute
  AuthenticatedLabsIndexRoute: typeof AuthenticatedLabsIndexRoute
  AuthenticatedSamIndexRoute: typeof AuthenticatedSamIndexRoute
  AuthenticatedLabsCommitmentsIdRoute: typeof AuthenticatedLabsCommitmentsIdRoute
  AuthenticatedLabsProposalsIdRoute: typeof AuthenticatedLabsProposalsIdRoute
  AuthenticatedSamMissionsIdRoute: typeof AuthenticatedSamMissionsIdRoute
  AuthenticatedLabsProposalsIndexRoute: typeof AuthenticatedLabsProposalsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountabilityRoute: AuthenticatedAccountabilityRoute,
  AuthenticatedContentOpsRoute: AuthenticatedContentOpsRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedVenturesRoute: AuthenticatedVenturesRoute,
  AuthenticatedLabsAccountabilityRoute: AuthenticatedLabsAccountabilityRoute,
  AuthenticatedLabsBillingRoute: AuthenticatedLabsBillingRoute,
  AuthenticatedLabsDecisionsRoute: AuthenticatedLabsDecisionsRouteWithChildren,
  AuthenticatedLabsDocumentsRoute: AuthenticatedLabsDocumentsRouteWithChildren,
  AuthenticatedLabsGoalsRoute: AuthenticatedLabsGoalsRouteWithChildren,
  AuthenticatedLabsKnowledgeRoute: AuthenticatedLabsKnowledgeRouteWithChildren,
  AuthenticatedLabsMissionControlRoute: AuthenticatedLabsMissionControlRoute,
  AuthenticatedLabsOperatorRoute: AuthenticatedLabsOperatorRoute,
  AuthenticatedLabsProjectsRoute: AuthenticatedLabsProjectsRouteWithChildren,
  AuthenticatedLabsRevenueRoute: AuthenticatedLabsRevenueRoute,
  AuthenticatedLabsVenturesRoute: AuthenticatedLabsVenturesRouteWithChildren,
  AuthenticatedSamContentRoute: AuthenticatedSamContentRouteWithChildren,
  AuthenticatedSamControlRoute: AuthenticatedSamControlRoute,
  AuthenticatedSamIntegrationsRoute:
    AuthenticatedSamIntegrationsRouteWithChildren,
  AuthenticatedSamMemoryRoute: AuthenticatedSamMemoryRoute,
  AuthenticatedLabsIndexRoute: AuthenticatedLabsIndexRoute,
  AuthenticatedSamIndexRoute: AuthenticatedSamIndexRoute,
  AuthenticatedLabsCommitmentsIdRoute: AuthenticatedLabsCommitmentsIdRoute,
  AuthenticatedLabsProposalsIdRoute: AuthenticatedLabsProposalsIdRoute,
  AuthenticatedSamMissionsIdRoute: AuthenticatedSamMissionsIdRoute,
  AuthenticatedLabsProposalsIndexRoute: AuthenticatedLabsProposalsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ProposalTokenRoute: ProposalTokenRoute,
  ApiPublicAutomationSchedulerRoute: ApiPublicAutomationSchedulerRoute,
  ApiPublicAutomationTickRoute: ApiPublicAutomationTickRoute,
  ApiPublicProposalsAcceptRoute: ApiPublicProposalsAcceptRoute,
  ApiPublicProposalsDeclineRoute: ApiPublicProposalsDeclineRoute,
  ApiPublicProposalsPdfRoute: ApiPublicProposalsPdfRoute,
  ApiPublicProposalsViewRoute: ApiPublicProposalsViewRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicMediaMetaDeliveryTokenRoute: ApiPublicMediaMetaDeliveryTokenRoute,
  ApiPublicOauthMetaAuthorizeRoute: ApiPublicOauthMetaAuthorizeRoute,
  ApiPublicOauthMetaCallbackRoute: ApiPublicOauthMetaCallbackRoute,
  ApiPublicOauthMetaDataDeletionRoute: ApiPublicOauthMetaDataDeletionRoute,
  ApiPublicOauthMetaDeauthorizeRoute: ApiPublicOauthMetaDeauthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
