/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVenturesRouteImport } from './routes/_authenticated/ventures'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedAccountabilityRouteImport } from './routes/_authenticated/accountability'
import { Route as AuthenticatedVenturesIdRouteImport } from './routes/_authenticated/ventures.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVenturesRoute = AuthenticatedVenturesRouteImport.update({
  id: '/_authenticated/ventures',
  path: '/ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/_authenticated/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/_authenticated/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/_authenticated/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/_authenticated/integrations',
    path: '/integrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/_authenticated/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountabilityRoute =
  AuthenticatedAccountabilityRouteImport.update({
    id: '/_authenticated/accountability',
    path: '/accountability',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVenturesIdRoute = AuthenticatedVenturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVenturesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/accountability': typeof AuthenticatedAccountabilityRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ventures': typeof AuthenticatedVenturesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/ventures/$id': typeof AuthenticatedVenturesIdRoute
}
export interface FileRoutesByTo {
  '/accountability': typeof AuthenticatedAccountabilityRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ventures': typeof AuthenticatedVenturesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/ventures/$id': typeof AuthenticatedVenturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/accountability': typeof AuthenticatedAccountabilityRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/ventures': typeof AuthenticatedVenturesRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ventures/$id': typeof AuthenticatedVenturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accountability'
    | '/decisions'
    | '/integrations'
    | '/knowledge'
    | '/operator'
    | '/projects'
    | '/settings'
    | '/ventures'
    | '/'
    | '/ventures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accountability'
    | '/decisions'
    | '/integrations'
    | '/knowledge'
    | '/operator'
    | '/projects'
    | '/settings'
    | '/ventures'
    | '/'
    | '/ventures/$id'
  id:
    | '__root__'
    | '/_authenticated/accountability'
    | '/_authenticated/decisions'
    | '/_authenticated/integrations'
    | '/_authenticated/knowledge'
    | '/_authenticated/operator'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/ventures'
    | '/_authenticated/'
    | '/_authenticated/ventures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAccountabilityRoute: typeof AuthenticatedAccountabilityRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVenturesRoute: typeof AuthenticatedVenturesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventures': {
      id: '/_authenticated/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof AuthenticatedVenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accountability': {
      id: '/_authenticated/accountability'
      path: '/accountability'
      fullPath: '/accountability'
      preLoaderRoute: typeof AuthenticatedAccountabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventures/$id': {
      id: '/_authenticated/ventures/$id'
      path: '/$id'
      fullPath: '/ventures/$id'
      preLoaderRoute: typeof AuthenticatedVenturesIdRouteImport
      parentRoute: typeof AuthenticatedVenturesRoute
    }
  }
}

interface AuthenticatedVenturesRouteChildren {
  AuthenticatedVenturesIdRoute: typeof AuthenticatedVenturesIdRoute
}

const AuthenticatedVenturesRouteChildren: AuthenticatedVenturesRouteChildren = {
  AuthenticatedVenturesIdRoute: AuthenticatedVenturesIdRoute,
}

const AuthenticatedVenturesRouteWithChildren =
  AuthenticatedVenturesRoute._addFileChildren(
    AuthenticatedVenturesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAccountabilityRoute: AuthenticatedAccountabilityRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVenturesRoute: AuthenticatedVenturesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
